import type { FC } from "react";

interface SchemaMarkupProps {
  /** Single schema object or combined @graph */
  schema: object;
  /** Optional key for React rendering */
  id?: string;
}

/**
 * Renders JSON-LD structured data into the page <head>.
 * Works with any schema generated by lib/schema.ts.
 *
 * Usage:
 *   <SchemaMarkup schema={generateArticleSchema({ ... })} />
 *   <SchemaMarkup schema={combineSchemas(org, web, faq)} />
 */
const SchemaMarkup: FC<SchemaMarkupProps> = ({ schema, id }) => {
  return (
    <script
      id={id}
      type="application/ld+json"
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(schema, null, 2),
      }}
    />
  );
};

export default SchemaMarkup;
